all:
	python main.py train.csv validation.csv test.csv output1.csv linear
	python main.py train.csv validation.csv test.csv output2.csv ridge
3.1:
    python run.py "linear_regression"
3.2:
    python run.py "ridge_regression"
3.4:
    python run.py "skl"
3.5:
    python run.py "features"
3.6.1:
    python run.py "visualisation_normal"
3.6.2:
    python run.py "visualisation_features"
3.7:
    python run.py "last"